


-- Key	Description
-- <c-d>	delete currently selected project
-- <c-v>	rename currently selected project
-- <c-a>	create a project*
-- <c-s>	search inside files within your project
-- <c-b>	browse inside files within your project
-- <c-l>	change to the selected project's directory without opening it
-- <c-r>	find a recently opened file within your project
-- <c-f>	find a file within your project (same as <CR>)
-- <c-w>	change workspace

-- require'telescope'.extensions.project.project{}`
-- require'telescope'.load_extension('project')
-- require'telescope'.extensions.project.project{}
-- require('telescope').setup {
--   local project_actions = require("telescope._extensions.project.actions")
--   extensions = {
--     project = {
--       base_dirs = {
--         '~/dev/src',
--         {'~/dev/src2'},
--         {'~/dev/src3', max_depth = 4},
--         {path = '~/dev/src4'},
--         {path = '~/dev/src5', max_depth = 2},
--       },
--       hidden_files = true, -- default: false
--       theme = "dropdown",
--       order_by = "asc",
--       search_by = "title",
--       sync_with_nvim_tree = true, -- default false
--       -- default for on_project_selected = find project files
--       on_project_selected = function(prompt_bufnr)
--         -- Do anything you want in here. For example:
--         project_actions.change_working_directory(prompt_bufnr, false)
--         require("harpoon.ui").nav_file(1)
--       end
--     }
--   }
-- }
